### ISSUE TITLE
라이브 쇼핑 현황 팝업창 화면 깜빡임 동작 안함

### ISSUE THREAD

**Issue by leejineun** [whileTrueDev/project-lc#259]
### 버그를 설명해 주세요.
라이브 쇼핑 현황 팝업창 알림시 화면 깜빡임 없이 소리만 납니다.

### 재현 방법
가입 후, 아이디 불러주시면, 해당 아이디로 라이브쇼핑 매칭 시키겠습니다.
마이페이지에서 라이브쇼핑 현황 창 띄우고, 오버레이 컨트롤러에서 메세지 전송 후, 알림 버튼을 클릭을 합니다.

### 버그의 해결 방향
알림 받는 이벤트가 화면 깜빡임을 발생 시키지 않는 것 같습니다.

### 환경
버그가 발견된 환경을 설명해주세요.

- OS: [e.g. iOS] windows
- Browser: [e.g. chrome, safari] chrome
- Version: [e.g. 22]
- Environment: [e.g. prod, dev or test] production

**Comment by hwasurr** [comment]
테스트서버환경에서도 동일하게 발생합니다
