### ISSUE TITLE
방송인센터 - 시작가이드 - 데이터 입력 오류

### ISSUE THREAD

**Issue by jiyeon2** [whileTrueDev/project-lc#310]
### 버그를 설명해 주세요.

방송인센터 시작가이드에서 데이터 입력시 간헐적으로 오류 발생

![스크린샷 2022-03-30 오후 4 31 23](https://user-images.githubusercontent.com/18395475/160776253-b3137971-58f9-4070-bcc3-99de523481d7.png)
=> 재연 못함
![스크린샷 2022-03-30 오후 4 32 25](https://user-images.githubusercontent.com/18395475/160776408-7a9f841f-93bd-4fc2-ba4e-803c69e94263.png)
=> 별다른 처리 없디 갑자기 해결되었던가 그랬던 걸로 기억

### 재현 방법
재연 방법 모르겠음 

### 버그의 해결 방향
에러 발생 원인, 조건 불명. 같은 문제 재발하지 않기 위해 방송인센터 시작가이드 입력부분 기능 확인 필요
(작성란)

### 환경
버그가 발견된 환경을 설명해주세요.

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Environment: [e.g. prod, dev or test]

### 추가 설명
추가설명을 작성하세요. 없다면 넘기셔도 좋습니다.

**Comment by leejineun** [comment]
이전의 에러 내용도 추가하자면, 방송인 샘플 주소 등록시, 원인미상의 PUT 401에러가 발생했었습니다.
당시에도 아무런 수정없이 재시도하니 다시 됐습니다.
